name: identity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  flex_color_scheme: ^8.1.1
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  auto_size_text: ^3.0.0
  realm: ^20.0.1
  forui: ^0.9.1+1
  forui_assets: ^0.9.1
  disclosure: ^2.2.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  wolt_modal_sheet: ^0.11.0
  signals: ^6.0.2
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
